const { GoogleGenerativeAI, HarmCategory, HarmBlockThreshold } = require('@google/generative-ai');
const config = require('../config/config');

let genAI;
let model;

/**
 * Initializes the Google Generative AI client and model.
 * @throws {Error} If Google API key is missing.
 */
function initializeLLM() {
    if (!config.googleApiKey) {
        throw new Error('Google API Key (GOOGLE_API_KEY) is not configured in .env');
    }
    if (!genAI) {
        console.log('[LLM Service] Initializing Google Generative AI...');
        genAI = new GoogleGenerativeAI(config.googleApiKey);
        model = genAI.getGenerativeModel({
            model: 'gemini-1.5-flash', // Or another suitable model
            // Safety settings can be adjusted if needed
            // safetySettings: [
            //     { category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
            //     { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
            // ],
        });
        console.log('[LLM Service] Google Generative AI initialized.');
    }
}

/**
 * Translates the given text to the target language using the configured LLM.
 * @param {string} text The text to translate.
 * @param {string} targetLanguage The target language (e.g., 'Spanish').
 * @returns {Promise<string>} The translated text.
 * @throws {Error} If initialization fails or translation API call fails.
 */
async function translateText(text, targetLanguage) {
    initializeLLM(); // Ensure LLM is initialized

    if (!text || text.trim().length === 0) {
        console.log('[LLM Service] Skipping translation for empty text.');
        return '';
    }

    // Refined prompt acknowledging input source and handling inaccuracies
    const prompt = `You are acting as a real-time translator. The following input is a live English transcription generated by Azure Speech-to-Text, which may contain inaccuracies or misheard words.

Your task is to translate this transcription into ${targetLanguage}. Prioritize translating the *intended meaning* based on the context. If parts of the transcription seem nonsensical due to likely transcription errors, use your best judgment to infer the speaker's intent while remaining as faithful as possible to the original meaning. However, if the transcription appears reasonably coherent, translate it directly.

Output *only* the final ${targetLanguage} translation, without any explanations, commentary, or introductory phrases like "Here is the translation:".

Input Transcription:
"${text}"

${targetLanguage} Translation:`; // Added label for clarity but LLM should ignore based on instructions

    // For demonstration purposes, print the exact prompt that will be sent:
    console.log("--- LLM Prompt ---");
    console.log(prompt);
    console.log("--- End LLM Prompt ---");

    try {
        console.log(`[LLM Service] Sending text to Gemini for translation to ${targetLanguage}...`);
        const result = await model.generateContent(prompt);
        const response = result.response;
        const translatedText = response.text().trim();
        console.log(`[LLM Service] Received translation: "${translatedText}"`);
        return translatedText;
    } catch (error) {
        console.error('[LLM Service] Error during translation API call:', error);
        // Check for specific safety/block reasons
        if (error.response && error.response.promptFeedback && error.response.promptFeedback.blockReason) {
             throw new Error(`Translation blocked due to safety settings: ${error.response.promptFeedback.blockReason}`);
        } else if (error instanceof Error) {
             throw new Error(`LLM API Error: ${error.message}`);
        } else {
            throw new Error('Unknown error during LLM translation');
        }
    }
}

module.exports = {
    translateText,
}; 