const { GoogleGenerativeAI, HarmCategory, HarmBlockThreshold } = require('@google/generative-ai');
const config = require('../config/config');

let genAI;
let model;

/**
 * Initializes the Google Generative AI client and model.
 * @throws {Error} If Google API key is missing.
 */
function initializeLLM() {
    if (!config.googleApiKey) {
        throw new Error('Google API Key (GOOGLE_API_KEY) is not configured in .env');
    }
    if (!genAI) {
        console.log('[LLM Service] Initializing Google Generative AI...');
        genAI = new GoogleGenerativeAI(config.googleApiKey);
        model = genAI.getGenerativeModel({
            model: 'models/gemini-2.0-flash',
            // Safety settings can be adjusted if needed
            // safetySettings: [
            //     { category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
            //     { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
            // ],
        });
        console.log('[LLM Service] Google Generative AI initialized.');
    }
}

/**
 * Translates the given text to the target language using the configured LLM.
 * @param {string} text The text to translate.
 * @param {string} targetLanguage The target language (e.g., 'Spanish').
 * @returns {Promise<string>} The translated text.
 * @throws {Error} If initialization fails or translation API call fails.
 */
async function translateText(text, targetLanguage) {
    initializeLLM(); // Ensure LLM is initialized

    if (!text || text.trim().length === 0) {
        console.log('[LLM Service] Skipping translation for empty text.');
        return '';
    }

    // Refined prompt acknowledging input source and handling inaccuracies
    const prompt = `You are acting as a real-time translator. The following input is a live English transcription generated by Azure Speech-to-Text, which may contain inaccuracies or misheard words.

Your task is to translate this transcription into ${targetLanguage}. Prioritize translating the *intended meaning* based on the context. If parts of the transcription seem nonsensical due to likely transcription errors, use your best judgment to infer the speaker's intent while remaining as faithful as possible to the original meaning. However, if the transcription appears reasonably coherent, translate it directly.

Output *only* the final ${targetLanguage} translation, without any explanations, commentary, or introductory phrases like "Here is the translation:".

Input Transcription:
"${text}"

${targetLanguage} Translation:`; // Added label for clarity but LLM should ignore based on instructions

    // For demonstration purposes, print the exact prompt that will be sent:
    console.log("--- LLM Prompt ---");
    console.log(prompt);
    console.log("--- End LLM Prompt ---");

    try {
        console.log(`[LLM Service] Sending text to Gemini for translation to ${targetLanguage}...`);
        const result = await model.generateContent(prompt);
        const response = result.response;
        const translatedText = response.text().trim();
        console.log(`[LLM Service] Received translation: "${translatedText}"`);
        return translatedText;
    } catch (error) {
        console.error('[LLM Service] Error during translation API call:', error);
        // Check for specific safety/block reasons
        if (error.response && error.response.promptFeedback && error.response.promptFeedback.blockReason) {
             throw new Error(`Translation blocked due to safety settings: ${error.response.promptFeedback.blockReason}`);
        } else if (error instanceof Error) {
             throw new Error(`LLM API Error: ${error.message}`);
        } else {
            throw new Error('Unknown error during LLM translation');
        }
    }
}

/**
 * Batch translates text to multiple target languages in one API call.
 * @param {string} text The text to translate.
 * @param {string[]} targetLanguages The target languages (e.g., ['Spanish', 'Portuguese', ...]).
 * @returns {Promise<Object>} An object mapping each language to its translation.
 */
async function batchTranslateText(text, targetLanguages) {
    initializeLLM();
    if (!text || text.trim().length === 0) {
        console.log('[LLM Service] Skipping translation for empty text batch.');
        return targetLanguages.reduce((acc, lang) => {
            acc[lang] = '';
            return acc;
        }, {});
    }

    // Format languages as a comma-separated list
    const langsList = targetLanguages.join(', ');
    
    // Prepare prompt
    const prompt = `You are acting as a real-time interpreter. The following input is a live English transcription generated by a voice-to-text model, which may contain inaccuracies or misheard words. Your task is to translate this transcription into the following languages in order: ${langsList}. Output the translations in that order, separated by double slashes (//), with no extra text. If the transcription does not make sense, use your best judgment to infer the speaker's intent and act as an interpreter, but if it does, be as faithful as possible to the meaning.\n\nInput: "${text}"\n\nTranslations:`;
    console.log("--- LLM Batch Prompt ---");
    console.log(prompt);
    console.log("--- End LLM Batch Prompt ---");

    try {
        console.log(`[LLM Service] Sending text to Gemini for batch translation to: ${langsList}`);
        const result = await model.generateContent({ contents: [{ parts: [{ text: prompt }] }] });
        const response = result.response;
        const translationText = response.text().trim();
        console.log(`[LLM Service] Received batch translation: "${translationText}"`);
        
        // Split translations by delimiter and map to languages
        const translations = translationText.split('//').map(t => t.trim());
        const result_map = {};
        
        // Match each translation with its language
        targetLanguages.forEach((lang, index) => {
            result_map[lang] = index < translations.length ? translations[index] : `[Failed to translate to ${lang}]`;
        });
        
        return result_map;
    } catch (error) {
        console.error('[LLM Service] Error during batch translation:', error);
        
        if (error.response && error.response.promptFeedback && error.response.promptFeedback.blockReason) {
             throw new Error(`Batch translation blocked due to safety settings: ${error.response.promptFeedback.blockReason}`);
        }
        
        throw new Error(`Translation API Error: ${error.message}`);
    }
}

/**
 * Gets a Spanish dictionary-style definition for the given English word.
 * @param {string} word The English word to define.
 * @returns {Promise<Object>} The definition object with Spanish definition and example.
 * @throws {Error} If initialization fails or API call fails.
 */
async function getWordDefinition(word) {
    initializeLLM(); // Ensure LLM is initialized

    if (!word || word.trim().length === 0) {
        console.log('[LLM Service] Skipping definition for empty word.');
        return { definition: '', example: '' };
    }

    const prompt = `You are acting as a bilingual dictionary for Spanish speakers learning English. Your job is to help a Spanish-speaking learner understand the English word "${word}".

Provide a SIMPLE explanation in Spanish of what this English word means. Use basic vocabulary a beginner would understand. Do NOT just translate it—explain the concept clearly, using examples if helpful.

Your response must be in JSON format with exactly these fields:
{
  "translation": "A direct Spanish translation of the word (1-3 words)",
  "definition": "A VERY simple explanation in Spanish of what the word means (1-2 short sentences, using basic vocabulary)",
  "example": "A simple example sentence in English that uses this word. The word itself should appear in the sentence.",
  "partOfSpeech": "The part of speech (noun, verb, adjective, etc.)",
  "frequencyRating": "A number from 1 to 5 representing how common this word is in everyday English, where 1 = extremely common (basic vocabulary), 2 = very common, 3 = moderately common, 4 = somewhat uncommon, 5 = rare or specialized",
  "imagePrompt": "A detailed prompt to generate a clear, educational, animated-style illustration of this word. The image should be in a friendly cartoon style with bright colors and simple background."
}

Only return the JSON object, nothing else.`;

    console.log(`[LLM Service] Getting Spanish definition for: "${word}"`);
    console.log(`--- LLM Definition Prompt ---`);
    console.log(prompt);
    console.log(`--- End LLM Definition Prompt ---`);

    try {
        const result = await model.generateContent(prompt);
        const response = result.response;
        const text = response.text().trim();
        console.log(`[LLM Service] Received definition response: "${text.substring(0, 100)}..."`);
        
        // Extract JSON from response
        try {
            // First try to directly parse the text, stripping code fences if present
            const cleanedText = text.replace(/```(?:json)?\s*([\s\S]*?)\s*```/g, '$1');
            let jsonResponse = JSON.parse(cleanedText);
            
            // Generate image if we have a prompt
            if (jsonResponse.imagePrompt) {
                try {
                    const imageUrl = await generateImage(jsonResponse.imagePrompt);
                    jsonResponse.imageUrl = imageUrl;
                } catch (imageError) {
                    console.error('[LLM Service] Error generating image:', imageError);
                    jsonResponse.imageUrl = null; // null indicates loading state
                }
            }
            
            return jsonResponse;
        } catch (jsonError) {
            console.error('[LLM Service] Error parsing definition JSON:', jsonError);
            console.error('[LLM Service] Raw response was:', text);
            
            // Try to extract JSON from text if it's wrapped in code blocks or has extra text
            const jsonMatch = text.match(/```(?:json)?\s*(\{[\s\S]*?\})\s*```|(\{[\s\S]*?\})/);
            if (jsonMatch) {
                const jsonContent = (jsonMatch[1] || jsonMatch[2]).trim();
                try {
                    const jsonResponse = JSON.parse(jsonContent);
                    
                    // Generate image if we have a prompt
                    if (jsonResponse.imagePrompt) {
                        try {
                            const imageUrl = await generateImage(jsonResponse.imagePrompt);
                            jsonResponse.imageUrl = imageUrl;
                        } catch (imageError) {
                            console.error('[LLM Service] Error generating image:', imageError);
                            jsonResponse.imageUrl = null; // null indicates loading state
                        }
                    }
                    
                    return jsonResponse;
                } catch (nestedJsonError) {
                    console.error('[LLM Service] Error parsing extracted JSON:', nestedJsonError);
                }
            }
            
            // Return a formatted error as the definition
            return {
                translation: word,
                definition: "Error obteniendo definición",
                example: "N/A",
                partOfSpeech: "unknown"
            };
        }
    } catch (error) {
        console.error('[LLM Service] Error during definition API call:', error);
        return {
            translation: word,
            definition: "API error: " + (error.message || "Unknown error"),
            example: "",
            partOfSpeech: ""
        };
    }
}

/**
 * Generates an image based on the provided prompt using OpenAI's DALL-E API
 * @param {string} prompt - The prompt to generate an image for
 * @returns {Promise<string>} - URL of the generated image
 */
async function generateImage(prompt) {
    const openaiApiKey = process.env.OPENAI_API_KEY;
    
    if (!openaiApiKey) {
        throw new Error('OpenAI API key is not configured');
    }
    
    try {
        console.log(`[Image Generation] Generating image for prompt: ${prompt.substring(0, 50)}...`);
        
        const response = await fetch('https://api.openai.com/v1/images/generations', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${openaiApiKey}`
            },
            body: JSON.stringify({
                model: "dall-e-3",
                prompt: prompt,
                n: 1,
                size: "1024x1024",
                quality: "standard", // Use standard to save costs
                response_format: "url"
            })
        });
        
        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`DALL-E API error: ${response.status} ${errorText}`);
        }
        
        const data = await response.json();
        console.log('[Image Generation] Successfully generated image');
        
        return data.data[0].url;
    } catch (error) {
        console.error('[Image Generation] Error:', error);
        throw error;
    }
}

/**
 * Generates speech audio from text using OpenAI TTS API
 * @param {string} text - The text to convert to speech
 * @param {string} voice - The voice to use (default: 'alloy')
 * @returns {Promise<Buffer>} - Audio data as buffer
 */
async function generateSpeech(text, voice = 'alloy') {
    const openaiApiKey = process.env.OPENAI_API_KEY;
    
    if (!openaiApiKey) {
        throw new Error('OpenAI API key is not configured');
    }
    
    try {
        console.log(`[TTS] Generating speech for: "${text.substring(0, 50)}..."`);
        
        const response = await fetch('https://api.openai.com/v1/audio/speech', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${openaiApiKey}`
            },
            body: JSON.stringify({
                model: "tts-1",
                voice: voice,
                input: text,
                response_format: "mp3"
            })
        });
        
        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`TTS API error: ${response.status} ${errorText}`);
        }
        
        const buffer = await response.arrayBuffer();
        console.log('[TTS] Successfully generated speech audio');
        
        return Buffer.from(buffer);
    } catch (error) {
        console.error('[TTS] Error:', error);
        throw error;
    }
}

module.exports = {
    translateText,
    batchTranslateText,
    getWordDefinition,
    generateImage,
    generateSpeech
}