/**
 * Centralized LLM Service for Polycast
 * Manages all interactions with the Google Generative AI (Gemini) API
 */
import { GoogleGenerativeAI, HarmCategory, HarmBlockThreshold } from "@google/generative-ai";

// Simple approach for TypeScript to ignore process variable errors
// This works because we know the code will run in a Node.js environment on render.com
// @ts-ignore
const apiKey = (process as any).env.GOOGLE_API_KEY || "";

// Check for API key before any imports to fail fast
if (!apiKey) {
  console.error("ERROR: No GOOGLE_API_KEY found in environment variables. Gemini features will not work.");
}

// Initialize the Gemini client with API key
const genAI = new GoogleGenerativeAI(apiKey);

// Export the model - using gemini-2.0-flash as requested
export const geminiModel = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });

/**
 * Generate content using Gemini API with the specified prompt
 * 
 * @param prompt - The prompt to send to Gemini
 * @returns The response text from Gemini
 */
export async function generateContent(prompt: string): Promise<string> {
  console.log(`[LLM Service] Generating content with prompt: ${prompt.substring(0, 100)}...`);
  
  try {
    const result = await geminiModel.generateContent(prompt);
    const response = result.response.text().trim();
    console.log(`[LLM Service] Received response: ${response.substring(0, 100)}...`);
    return response;
  } catch (error) {
    console.error('[LLM Service] Error during content generation:', error);
    throw error;
  }
}

/**
 * Generate flashcard content using Gemini
 * 
 * @param prompt - The prompt to generate flashcard content
 * @returns The generated flashcard content as JSON string
 */
export async function generateFlashcardContent(prompt: string): Promise<string> {
  console.log(`[LLM Service] Generating flashcard content with prompt: ${prompt.substring(0, 100)}...`);
  
  try {
    const result = await geminiModel.generateContent(prompt);
    const response = result.response.text().trim();
    console.log(`[LLM Service] Received flashcard content: ${response.substring(0, 100)}...`);
    return response;
  } catch (error) {
    console.error('[LLM Service] Error generating flashcard content:', error);
    throw error;
  }
}

/**
 * Translates text to a target language
 * 
 * @param text - The text to translate
 * @param targetLanguage - The target language to translate to
 * @returns The translated text
 */
export async function translateText(text: string, targetLanguage: string): Promise<string> {
  if (!text || text.trim().length === 0) {
    console.log('[LLM Service] Skipping translation for empty text.');
    return '';
  }

  const prompt = `You are acting as a real-time translator. The following input is a live English transcription generated by a voice-to-text model, which may contain inaccuracies or misheard words.

Your task is to translate this transcription into ${targetLanguage}. Prioritize translating the *intended meaning* based on the context. If parts of the transcription seem nonsensical due to likely transcription errors, use your best judgment to infer the speaker's intent while remaining as faithful as possible to the original meaning. However, if the transcription appears reasonably coherent, translate it directly.

Output *only* the final ${targetLanguage} translation, without any explanations, commentary, or introductory phrases like "Here is the translation:".

Input Transcription:
"${text}"

${targetLanguage} Translation:`;

  console.log(`[LLM Service] Sending text to Gemini for translation to ${targetLanguage}...`);
  
  try {
    return await generateContent(prompt);
  } catch (error) {
    console.error('[LLM Service] Error during translation:', error);
    throw new Error(`Translation failed: ${error.message}`);
  }
}

/**
 * Batch translates text into multiple target languages
 * 
 * @param text - The text to translate
 * @param targetLanguages - Array of target languages
 * @returns Object mapping each language to its translation
 */
export async function translateTextBatch(text: string, targetLanguages: string[]): Promise<Record<string, string>> {
  if (!text || text.trim().length === 0) {
    console.log('[LLM Service] Skipping translation for empty text batch.');
    return Object.fromEntries(targetLanguages.map(lang => [lang, '']));
  }

  const langsList = targetLanguages.join(', ');
  const prompt = `You are acting as a real-time interpreter. The following input is a live English transcription generated by a voice-to-text model, which may contain inaccuracies or misheard words. Your task is to translate this transcription into the following languages in order: ${langsList}. Output the translations in that order, separated by double slashes (//), with no extra text. If the transcription does not make sense, use your best judgment to infer the speaker's intent and act as an interpreter, but if it does, be as faithful as possible to the meaning.

Input: "${text}"

Translations:`;

  console.log(`[LLM Service] Sending text to Gemini for batch translation to: ${langsList}`);
  
  try {
    const translationsRaw = await generateContent(prompt);
    
    // Split by // and map to languages
    const translationArr = translationsRaw.split(/\s*\/\/\s*/);
    const translations: Record<string, string> = {};
    
    for (let i = 0; i < targetLanguages.length; ++i) {
      translations[targetLanguages[i]] = translationArr[i] ? translationArr[i].trim() : '';
    }
    
    return translations;
  } catch (error) {
    console.error('[LLM Service] Error during batch translation:', error);
    throw new Error(`Batch translation failed: ${error.message}`);
  }
}

/**
 * Helper to extract JSON from LLM response text
 */
export function extractJsonFromText(text: string): any {
  try {
    // Find JSON in the response (it might be wrapped in code blocks or not)
    let jsonMatch = text.match(/```(?:json)?([^`]*?)```/s);
    let jsonStr = jsonMatch ? jsonMatch[1].trim() : text;
    
    // If still not JSON object, try to find anything that looks like JSON
    if (!jsonStr.startsWith('{') && !jsonStr.startsWith('[')) {
      jsonMatch = text.match(/(\{.*\})/s);
      jsonStr = jsonMatch ? jsonMatch[0] : text;
    }
    
    // Try to parse the JSON
    return JSON.parse(jsonStr);
  } catch (e) {
    console.error('[LLM Service] Failed to parse JSON:', e);
    
    // Last resort - try to extract just the JSON object
    const lastMatch = text.match(/\{[^]*\}/);
    if (lastMatch) {
      try {
        return JSON.parse(lastMatch[0]);
      } catch (e2) {
        console.error('[LLM Service] Failed final JSON parse attempt:', e2);
        throw e2;
      }
    } else {
      throw e;
    }
  }
}
